// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetThemeBackgroundColors(arg1) {
  return window['go']['ui_colors']['uiColorsGenerator']['GetThemeBackgroundColors'](arg1);
}
