// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}
